#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.7
#  Jul 24, 2020 05:33:48 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 670x336+1359+718
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 6414 1431
    wm minsize $top 130 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Bierpong Scoreboard"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::combobox $top.tCo52 \
        -values 1920x1080 -font TkTextFont -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo52" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -justify left -text Auflösung 
    vTcl:DefineAlias "$top.tLa53" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu56 \
        -takefocus {} -text {New Game} 
    vTcl:DefineAlias "$top.tBu56" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa57 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -justify left -text Spieler-Heim 
    vTcl:DefineAlias "$top.tLa57" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa59 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -justify left -text {Spieler Auswärts} 
    vTcl:DefineAlias "$top.tLa59" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo63 \
        -font TkTextFont -state disabled -textvariable heimTeam \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo63" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo64 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo64" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa65 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -justify left -text Heimteam 
    vTcl:DefineAlias "$top.tLa65" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa67 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -justify left -text Auswärtsteam 
    vTcl:DefineAlias "$top.tLa67" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo68 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo68" "TCombobox4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tCo68
    ttk::combobox $top.tCo69 \
        -values {Test1 Test2 {}} -font TkTextFont -textvariable cbPlayerAway \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo69" "TCombobox5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tCo69
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu70 \
        -takefocus {} -text {Lade Teaminfos} 
    vTcl:DefineAlias "$top.tBu70" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe48 \
        -takefocus 0 
    vTcl:DefineAlias "$top.tSe48" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tCo52 \
        -in $top -x 140 -y 90 -width 142 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 10 -y 90 -width 65 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu56 \
        -in $top -x 290 -y 240 -width 86 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa57 \
        -in $top -x 300 -y 120 -width 116 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa59 \
        -in $top -x 300 -y 150 -width 120 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo63 \
        -in $top -x 140 -y 120 -width 143 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo64 \
        -in $top -x 140 -y 150 -height 21 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $top.tLa65 \
        -in $top -x 10 -y 120 -width 105 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa67 \
        -in $top -x 10 -y 150 -width 95 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo68 \
        -in $top -x 440 -y 120 -height 21 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $top.tCo69 \
        -in $top -x 440 -y 150 -width 143 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu70 \
        -in $top -x 410 -y 80 -width 206 -relwidth 0 -height 35 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe48 \
        -in $top -x 240 -y 210 -width 200 -anchor nw -bordermode inside 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

